# Generated by Django 5.2.7 on 2026-04-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='seccion',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
