# Generated by Django 5.2.7 on 2026-04-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_transaccion_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='grado',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='seccion',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=2),
        ),
    ]
