# Generated by Django 5.2.7 on 2026-04-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_estudiante_grado_alter_estudiante_seccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
