# Generated by Django 5.2.7 on 2026-04-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_terminos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='version_terminos',
            field=models.CharField(default='', max_length=10),
        ),
    ]
