# Generated by Django 5.2.7 on 2026-04-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_profile_fecha_aceptacion_profile_version_terminos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('terminos', 'Términos y Condiciones'), ('privacidad', 'Política de Privacidad')], max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Terminos',
        ),
    ]
