# Generated by Django 5.2.7 on 2026-04-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_documentolegal_delete_terminos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='acepta_privacidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='acepta_terminos',
        ),
        migrations.AddField(
            model_name='profile',
            name='version_privacidad',
            field=models.CharField(default='', max_length=10),
        ),
    ]
